dairy(no_dairy, 0).
dairy(curd, 92).
dairy(egg_custard, 126).
dairy(vanilla_custard, 102).
dairy(dairy_ice_cream, 167).
dairy(condensed_milk_with_sugar, 350).
dairy(condensed_milk_without_sugar, 160).
dairy(goat_milk, 72).
dairy(sheep_milk, 96).
dairy(skimmed_milk, 36).
dairy(skimmed_milk_powder, 373).
dairy(whole_milk_powder, 500).
dairy(whole_milk, 68).
dairy(semi_skimmed_milk, 49).
dairy(mousse, 177).
dairy(cream, 298).
dairy(low_fat_cottage_cheese, 70).
dairy(brie_cheese, 263).
dairy(camembert_cheese, 312).
dairy(cheddar_cheese, 381).
dairy(cream_cheese, 245).
dairy(edam_cheese, 349).
dairy(burgos_cheese, 174).
dairy(sheep_cheese, 245).
dairy(edam_cheese, 306).
dairy(emmental_cheese, 415).
dairy(processed_cheese_spread, 285).
dairy(gruyere_cheese, 391).
dairy(manchego_cheese, 376).
dairy(mozzarella_cheese, 245).
dairy(parmesan_cheese, 393).
dairy(ricotta_cheese, 400).
dairy(roquefort_cheese, 405).
dairy(cottage_cheese, 96).
dairy(low_fat_yogurt, 45).
dairy(low_fat_fruit_yogurt, 82).
dairy(cream_enriched_yogurt, 65).
dairy(natural_yogurt, 62).
dairy(natural_fruit_yogurt, 100).
